/*
 * Decompiled with CFR 0.152.
 */
package org.hibernate.dialect.identity;

import org.hibernate.dialect.identity.IdentityColumnSupportImpl;

public class H2IdentityColumnSupport
extends IdentityColumnSupportImpl {
    public static final H2IdentityColumnSupport INSTANCE = new H2IdentityColumnSupport();

    protected H2IdentityColumnSupport() {
    }

    @Override
    public boolean supportsIdentityColumns() {
        return true;
    }

    @Override
    public String getIdentityColumnString(int type) {
        return "generated by default as identity";
    }

    @Override
    public String getIdentitySelectString(String table, String column, int type) {
        return "call identity()";
    }

    @Override
    public String getIdentityInsertString() {
        return "default";
    }
}

