/*
 * Decompiled with CFR 0.152.
 */
package org.hibernate.dialect.identity;

import org.hibernate.dialect.identity.Ingres9IdentityColumnSupport;

public class Ingres10IdentityColumnSupport
extends Ingres9IdentityColumnSupport {
    @Override
    public boolean supportsIdentityColumns() {
        return true;
    }

    @Override
    public boolean hasDataTypeInIdentityColumn() {
        return true;
    }

    @Override
    public String getIdentityColumnString(int type) {
        return "not null generated by default as identity";
    }

    @Override
    public String getIdentityInsertString() {
        return "default";
    }
}

