/*
 * Decompiled with CFR 0.152.
 */
package org.apache.commons.httpclient;

import org.apache.commons.httpclient.HeaderElement;
import org.apache.commons.httpclient.HttpException;
import org.apache.commons.httpclient.NameValuePair;

public class Header
extends NameValuePair {
    private boolean isAutogenerated = false;

    public Header() {
        this(null, null);
    }

    public Header(String name, String value) {
        super(name, value);
    }

    public Header(String name, String value, boolean isAutogenerated) {
        super(name, value);
        this.isAutogenerated = isAutogenerated;
    }

    public String toExternalForm() {
        return (null == this.getName() ? "" : this.getName()) + ": " + (null == this.getValue() ? "" : this.getValue()) + "\r\n";
    }

    @Override
    public String toString() {
        return this.toExternalForm();
    }

    public HeaderElement[] getValues() throws HttpException {
        return HeaderElement.parse(this.getValue());
    }

    public HeaderElement[] getElements() {
        return HeaderElement.parseElements(this.getValue());
    }

    public boolean isAutogenerated() {
        return this.isAutogenerated;
    }
}

