/*
 * Decompiled with CFR 0.152.
 */
package org.codehaus.groovy.transform.stc;

public enum StaticTypesMarker {
    INFERRED_TYPE,
    DECLARATION_INFERRED_TYPE,
    INFERRED_RETURN_TYPE,
    CLOSURE_ARGUMENTS,
    READONLY_PROPERTY,
    INITIAL_EXPRESSION,
    DIRECT_METHOD_CALL_TARGET,
    DELEGATION_METADATA,
    IMPLICIT_RECEIVER,
    PV_FIELDS_ACCESS,
    PV_FIELDS_MUTATION,
    PV_METHODS_ACCESS,
    DYNAMIC_RESOLUTION,
    SUPER_MOP_METHOD_REQUIRED;

}

