/*
 * Decompiled with CFR 0.152.
 */
package com.atlassian.migration.agent.store.guardrails;

public enum QueryIds {
    ACTIVE_USERS,
    GROUP,
    ALL_USERS,
    BASE_USERS,
    CURRENT_ATT_PER_PAGE,
    EMBEDDED_ATT_PER_PAGE,
    RECENTLY_USED_SPACES,
    GROUPS_PER_USER,
    INACTIVE_USERS,
    JIRA_ISSUE_MACRO_TOP_100,
    JIRA_ISSUE_MACRO_TOP_K,
    LIST_OF_APPS_INSTALLED,
    MAX_COMMENTS_IN_PAGE,
    MAX_LIKE_IN_PAGE,
    MAX_NUMBER_OF_PAGES_IN_A_SPACE,
    MAX_SPACE_GROUP_PERMISSION_IN_SPACE,
    MAX_SPACE_PERMISSION_IN_SPACE,
    MAX_PAGE_WIDTH,
    MAX_RESTRICTIONS_IN_PAGE,
    MAX_SIZE_PERSONAL_SPACE,
    MAX_SPACE_USER_PERMISSION,
    MEDIA_SIZE,
    GROUPS_WITH_35K_OR_MORE_USER_MEMBERSHIPS,
    NUMBER_OF_GROUPS,
    NUMBER_OF_MACROS_PER_PAGE,
    NUMBER_OF_MEDIA_PER_PAGE,
    NUMBER_OF_SPACES,
    NUMBER_OF_SPACES_PER_SPACETYPE,
    NUMBER_OF_TABLES_PER_PAGE,
    PAGE_TREE_DEPTH,
    PAGES_WITH_RESTRICTIONS,
    PERSONAL_SPACES_INACTIVE_USERS,
    SIZE_OF_DB,
    SIZE_OF_NON_PERSONAL_SPACES,
    SIZE_OF_TABLES_PER_PAGE,
    SIZE_OF_TABLES,
    TOTAL_ATTACHMENTS_PER_PAGE,
    TOTAL_ATTACHMENTS_PER_SPACE,
    TOTAL_ATTACHMENTS,
    TOTAL_ATTACHMENTS_SIZE_GB,
    TOTAL_PAGES_PER_SPACE,
    TOTAL_PAGES_PER_VERSION,
    TOTAL_PAGES,
    TOTAL_BLOGPOSTS;

}

