/*
 * Decompiled with CFR 0.152.
 */
package org.bedework.util.xml.tagdefs;

import java.util.HashMap;
import javax.xml.namespace.QName;

public class WebdavTags {
    public static final String namespace = "DAV:";
    public static final HashMap<String, QName> qnames = new HashMap();
    public static final QName _abstract = WebdavTags.makeQName("abstract");
    public static final QName ace = WebdavTags.makeQName("ace");
    public static final QName acl = WebdavTags.makeQName("acl");
    public static final QName aclPrincipalPropSet = WebdavTags.makeQName("acl-principal-prop-set");
    public static final QName aclRestrictions = WebdavTags.makeQName("acl-restrictions");
    public static final QName addMember = WebdavTags.makeQName("add-member");
    public static final QName all = WebdavTags.makeQName("all");
    public static final QName allowedPrincipal = WebdavTags.makeQName("allowed-principal");
    public static final QName allprop = WebdavTags.makeQName("allprop");
    public static final QName alternateURISet = WebdavTags.makeQName("alternate-URI-set");
    public static final QName applyToPrincipalCollectionSet = WebdavTags.makeQName("apply-to-principal-collection-set");
    public static final QName authenticated = WebdavTags.makeQName("authenticated");
    public static final QName bind = WebdavTags.makeQName("bind");
    public static final QName collection = WebdavTags.makeQName("collection");
    public static final QName creationdate = WebdavTags.makeQName("creationdate");
    public static final QName currentUserPrincipal = WebdavTags.makeQName("current-user-principal");
    public static final QName currentUserPrivilegeSet = WebdavTags.makeQName("current-user-privilege-set");
    public static final QName deny = WebdavTags.makeQName("deny");
    public static final QName denyBeforeGrant = WebdavTags.makeQName("deny-before-grant");
    public static final QName description = WebdavTags.makeQName("description");
    public static final QName displayname = WebdavTags.makeQName("displayname");
    public static final QName error = WebdavTags.makeQName("error");
    public static final QName expandProperty = WebdavTags.makeQName("expand-property");
    public static final QName getcontentlanguage = WebdavTags.makeQName("getcontentlanguage");
    public static final QName getcontentlength = WebdavTags.makeQName("getcontentlength");
    public static final QName getcontenttype = WebdavTags.makeQName("getcontenttype");
    public static final QName getetag = WebdavTags.makeQName("getetag");
    public static final QName getlastmodified = WebdavTags.makeQName("getlastmodified");
    public static final QName grant = WebdavTags.makeQName("grant");
    public static final QName grantOnly = WebdavTags.makeQName("grant-only");
    public static final QName group = WebdavTags.makeQName("group");
    public static final QName groupMemberSet = WebdavTags.makeQName("group-member-set");
    public static final QName groupMembership = WebdavTags.makeQName("group-membership");
    public static final QName href = WebdavTags.makeQName("href");
    public static final QName inherited = WebdavTags.makeQName("inherited");
    public static final QName inheritedAclSet = WebdavTags.makeQName("inherited-acl-set");
    public static final QName invert = WebdavTags.makeQName("invert");
    public static final QName limit = WebdavTags.makeQName("limit");
    public static final QName limitedNumberOfAces = WebdavTags.makeQName("limited-number-of-aces");
    public static final QName lockdiscovery = WebdavTags.makeQName("lockdiscovery");
    public static final QName lockentry = WebdavTags.makeQName("lockentry");
    public static final QName lockscope = WebdavTags.makeQName("lockscope");
    public static final QName locktype = WebdavTags.makeQName("locktype");
    public static final QName match = WebdavTags.makeQName("match");
    public static final QName missingRequiredPrincipal = WebdavTags.makeQName("missing-required-principal");
    public static final QName mkcol = WebdavTags.makeQName("mkcol");
    public static final QName multistatus = WebdavTags.makeQName("multistatus");
    public static final QName needPrivileges = WebdavTags.makeQName("need-privileges");
    public static final QName noAbstract = WebdavTags.makeQName("no-abstract");
    public static final QName noAceConflict = WebdavTags.makeQName("no-ace-conflict");
    public static final QName noInheritedAceConflict = WebdavTags.makeQName("no-inherited-ace-conflict");
    public static final QName noInvert = WebdavTags.makeQName("no-invert");
    public static final QName noProtectedAceConflict = WebdavTags.makeQName("no-protected-ace-conflict");
    public static final QName notificationURL = WebdavTags.makeQName("notification-URL");
    public static final QName notSupportedPrivilege = WebdavTags.makeQName("not-supported-privilege");
    public static final QName owner = WebdavTags.makeQName("owner");
    public static final QName principal = WebdavTags.makeQName("principal");
    public static final QName principalCollectionSet = WebdavTags.makeQName("principal-collection-set");
    public static final QName principalMatch = WebdavTags.makeQName("principal-match");
    public static final QName principalProperty = WebdavTags.makeQName("principal-property");
    public static final QName principalPropertySearch = WebdavTags.makeQName("principal-property-search");
    public static final QName principalSearchProperty = WebdavTags.makeQName("principal-search-property");
    public static final QName principalSearchPropertySet = WebdavTags.makeQName("principal-search-property-set");
    public static final QName principalURL = WebdavTags.makeQName("principal-URL");
    public static final QName privilege = WebdavTags.makeQName("privilege");
    public static final QName prop = WebdavTags.makeQName("prop");
    public static final QName property = WebdavTags.makeQName("property");
    public static final QName propertySearch = WebdavTags.makeQName("property-search");
    public static final QName propertyUpdate = WebdavTags.makeQName("propertyupdate");
    public static final QName propfind = WebdavTags.makeQName("propfind");
    public static final QName propname = WebdavTags.makeQName("propname");
    public static final QName propstat = WebdavTags.makeQName("propstat");
    public static final QName _protected = WebdavTags.makeQName("protected");
    public static final QName quotaNotExceeded = WebdavTags.makeQName("quota-not-exceeded");
    public static final QName read = WebdavTags.makeQName("read");
    public static final QName readAcl = WebdavTags.makeQName("read-acl");
    public static final QName readCurrentUserPrivilegeSet = WebdavTags.makeQName("read-current-user-privilege-set");
    public static final QName recognizedPrincipal = WebdavTags.makeQName("recognized-principal");
    public static final QName remove = WebdavTags.makeQName("remove");
    public static final QName report = WebdavTags.makeQName("report");
    public static final QName requiredPrincipal = WebdavTags.makeQName("required-principal");
    public static final QName resource = WebdavTags.makeQName("resource");
    public static final QName resourceMustBeNull = WebdavTags.makeQName("resource-must-be-null");
    public static final QName resourcetype = WebdavTags.makeQName("resourcetype");
    public static final QName response = WebdavTags.makeQName("response");
    public static final QName responseDescription = WebdavTags.makeQName("responsedescription");
    public static final QName self = WebdavTags.makeQName("self");
    public static final QName set = WebdavTags.makeQName("set");
    public static final QName source = WebdavTags.makeQName("source");
    public static final QName status = WebdavTags.makeQName("status");
    public static final QName supportedPrivilege = WebdavTags.makeQName("supported-privilege");
    public static final QName supportedPrivilegeSet = WebdavTags.makeQName("supported-privilege-set");
    public static final QName supportedReport = WebdavTags.makeQName("supported-report");
    public static final QName supportedReportSet = WebdavTags.makeQName("supported-report-set");
    public static final QName syncCollection = WebdavTags.makeQName("sync-collection");
    public static final QName syncResponse = WebdavTags.makeQName("sync-response");
    public static final QName syncTraversalSupported = WebdavTags.makeQName("sync-traversal-supported");
    public static final QName synclevel = WebdavTags.makeQName("sync-level");
    public static final QName syncToken = WebdavTags.makeQName("sync-token");
    public static final QName supportedlock = WebdavTags.makeQName("supportedlock");
    public static final QName unauthenticated = WebdavTags.makeQName("unauthenticated");
    public static final QName unbind = WebdavTags.makeQName("unbind");
    public static final QName unlock = WebdavTags.makeQName("unlock");
    public static final QName validSyncToken = WebdavTags.makeQName("valid-sync-token");
    public static final QName whoami = WebdavTags.makeQName("whoami");
    public static final QName write = WebdavTags.makeQName("write");
    public static final QName writeAcl = WebdavTags.makeQName("write-acl");
    public static final QName writeContent = WebdavTags.makeQName("write-content");
    public static final QName writeProperties = WebdavTags.makeQName("write-properties");
    public static final QName application = WebdavTags.makeQName("application");
    public static final QName applications = WebdavTags.makeQName("applications");
    public static final QName features = WebdavTags.makeQName("features");
    public static final QName name = WebdavTags.makeQName("name");
    public static final QName serverinfo = WebdavTags.makeQName("server-info");
    public static final QName token = WebdavTags.makeQName("token");
    public static final QName accessControl = WebdavTags.makeQName("access-control");
    public static final QName class1 = WebdavTags.makeQName("class-1");
    public static final QName class2 = WebdavTags.makeQName("class-2");
    public static final QName class3 = WebdavTags.makeQName("class-3");
    public static final QName extendedMkcol = WebdavTags.makeQName("extended-mkcol");
    public static final QName quota = WebdavTags.makeQName("quota");
    public static final QName search = WebdavTags.makeQName("search");
    public static final QName versionControl = WebdavTags.makeQName("version-control");

    private static QName makeQName(String name) {
        QName q = new QName(namespace, name);
        qnames.put(name, q);
        return q;
    }
}

