/*
 * Decompiled with CFR 0.152.
 */
package com.atlassian.confluence.extra.calendar3.caldav;

public enum CalDavProperties {
    NONE(""),
    DURATION("DURATION"),
    DTSTART("DTSTART"),
    DTEND("DTEND"),
    DTSTAMP("DTSTAMP"),
    URL("URL"),
    ORGANIZER("ORGANIZER"),
    SUMMARY("SUMMARY"),
    DESCRIPTION("DESCRIPTION"),
    LOCATION("LOCATION"),
    ATTENDEE("ATTENDEE"),
    SEQUENCE("SEQUENCE"),
    LAST_MODIFIED("LAST-MODIFIED"),
    CREATED("CREATED"),
    RRULE("RRULE"),
    UID("UID"),
    RECURRENCE_ID("RECURRENCE-ID"),
    SUBCALENDAR_ID_PROPERTIES("SUBCALENDAR-ID"),
    PARENT_CALENDAR_ID_PROPERTIES("PARENT-CALENDAR-ID"),
    PARENT_CALENDAR_NAME_PROPERTIES("PARENT-CALENDAR-NAME"),
    SUBCALENDAR_NAME_PROPERTIES("SUBCALENDAR-NAME"),
    SUBCALENDAR_TZ_ID_PROPERTIES("SUBCALENDAR-TZ-ID"),
    PERIOD_REMINDER_PROPERTIES("PERIOD-REMINDER"),
    STORE_KEY_PROPERTIES("STORE-KEY-REMINDER"),
    EVENT_ID_PROPERTIES("EVENT-ID"),
    SUBSCRIPTION_ID_PROPERTIES("SUBSCRIPTION-ID"),
    CUSTOM_EVENTTYPE_ID_PROPERTIES("CUSTOM-EVENTTYPE-ID"),
    EVENT_ALLDAY_PROPERTIES("EVENT-ALLDAY"),
    EXTENDED_PROPERTY_JIRA_VIEW_BOARD_URL("viewBoardsUrl"),
    EXTENDED_PROPERTY_SPRINT_HOME_PAGE_URL("sprintHomePageUrl"),
    EXTENDED_PROPERTY_SUMMARY_LINK("summaryLink"),
    EXTENDED_PROPERTY_VIEW_ISSUE_LINK("viewIssuesLink"),
    EXTENDED_PROPERTY_ISSUE_LINK("issueLink"),
    EXTENDED_PROPERTY_RELEASE_NOTES_LINK("releaseNotesLink"),
    EXTENDED_PROPERTY_STATUS_TEXT("statusText"),
    EXTENDED_PROPERTY_RESOLVED("resolved"),
    EXTENDED_PROPERTY_ASSIGNEE_NAME("assigneeName"),
    EXTENDED_PROPERTY_DATE_FIELD("dateField"),
    EXTENDED_PROPERTY_ASSIGNEE_PROFILE_URL("assigneeProfileUrl"),
    JIRA_ISSUE_TYPE_CLASS_GREEN_HOPPER_SPRINT("greenhopper-sprint"),
    JIRA_ISSUE_TYPE_CLASS_JIRA_VERSION("jira-version"),
    JIRA_ISSUE_TYPE_CLASS_JIRA_ISSUE("jira-issue");

    private final String fieldName;

    public String getFieldName() {
        return this.fieldName;
    }

    private CalDavProperties(String fieldName) {
        this.fieldName = fieldName;
    }
}

