/*
 * Decompiled with CFR 0.152.
 */
package org.apache.bcel.generic;

import org.apache.bcel.generic.ArithmeticInstruction;
import org.apache.bcel.generic.ArrayInstruction;
import org.apache.bcel.generic.ConversionInstruction;
import org.apache.bcel.generic.Instruction;
import org.apache.bcel.generic.InstructionConst;
import org.apache.bcel.generic.LocalVariableInstruction;
import org.apache.bcel.generic.ReturnInstruction;
import org.apache.bcel.generic.StackInstruction;

@Deprecated
public interface InstructionConstants {
    public static final Instruction NOP = InstructionConst.NOP;
    public static final Instruction ACONST_NULL = InstructionConst.ACONST_NULL;
    public static final Instruction ICONST_M1 = InstructionConst.ICONST_M1;
    public static final Instruction ICONST_0 = InstructionConst.ICONST_0;
    public static final Instruction ICONST_1 = InstructionConst.ICONST_1;
    public static final Instruction ICONST_2 = InstructionConst.ICONST_2;
    public static final Instruction ICONST_3 = InstructionConst.ICONST_3;
    public static final Instruction ICONST_4 = InstructionConst.ICONST_4;
    public static final Instruction ICONST_5 = InstructionConst.ICONST_5;
    public static final Instruction LCONST_0 = InstructionConst.LCONST_0;
    public static final Instruction LCONST_1 = InstructionConst.LCONST_1;
    public static final Instruction FCONST_0 = InstructionConst.FCONST_0;
    public static final Instruction FCONST_1 = InstructionConst.FCONST_1;
    public static final Instruction FCONST_2 = InstructionConst.FCONST_2;
    public static final Instruction DCONST_0 = InstructionConst.DCONST_0;
    public static final Instruction DCONST_1 = InstructionConst.DCONST_1;
    public static final ArrayInstruction IALOAD = InstructionConst.IALOAD;
    public static final ArrayInstruction LALOAD = InstructionConst.LALOAD;
    public static final ArrayInstruction FALOAD = InstructionConst.FALOAD;
    public static final ArrayInstruction DALOAD = InstructionConst.DALOAD;
    public static final ArrayInstruction AALOAD = InstructionConst.AALOAD;
    public static final ArrayInstruction BALOAD = InstructionConst.BALOAD;
    public static final ArrayInstruction CALOAD = InstructionConst.CALOAD;
    public static final ArrayInstruction SALOAD = InstructionConst.SALOAD;
    public static final ArrayInstruction IASTORE = InstructionConst.IASTORE;
    public static final ArrayInstruction LASTORE = InstructionConst.LASTORE;
    public static final ArrayInstruction FASTORE = InstructionConst.FASTORE;
    public static final ArrayInstruction DASTORE = InstructionConst.DASTORE;
    public static final ArrayInstruction AASTORE = InstructionConst.AASTORE;
    public static final ArrayInstruction BASTORE = InstructionConst.BASTORE;
    public static final ArrayInstruction CASTORE = InstructionConst.CASTORE;
    public static final ArrayInstruction SASTORE = InstructionConst.SASTORE;
    public static final StackInstruction POP = InstructionConst.POP;
    public static final StackInstruction POP2 = InstructionConst.POP2;
    public static final StackInstruction DUP = InstructionConst.DUP;
    public static final StackInstruction DUP_X1 = InstructionConst.DUP_X1;
    public static final StackInstruction DUP_X2 = InstructionConst.DUP_X2;
    public static final StackInstruction DUP2 = InstructionConst.DUP2;
    public static final StackInstruction DUP2_X1 = InstructionConst.DUP2_X1;
    public static final StackInstruction DUP2_X2 = InstructionConst.DUP2_X2;
    public static final StackInstruction SWAP = InstructionConst.SWAP;
    public static final ArithmeticInstruction IADD = InstructionConst.IADD;
    public static final ArithmeticInstruction LADD = InstructionConst.LADD;
    public static final ArithmeticInstruction FADD = InstructionConst.FADD;
    public static final ArithmeticInstruction DADD = InstructionConst.DADD;
    public static final ArithmeticInstruction ISUB = InstructionConst.ISUB;
    public static final ArithmeticInstruction LSUB = InstructionConst.LSUB;
    public static final ArithmeticInstruction FSUB = InstructionConst.FSUB;
    public static final ArithmeticInstruction DSUB = InstructionConst.DSUB;
    public static final ArithmeticInstruction IMUL = InstructionConst.IMUL;
    public static final ArithmeticInstruction LMUL = InstructionConst.LMUL;
    public static final ArithmeticInstruction FMUL = InstructionConst.FMUL;
    public static final ArithmeticInstruction DMUL = InstructionConst.DMUL;
    public static final ArithmeticInstruction IDIV = InstructionConst.IDIV;
    public static final ArithmeticInstruction LDIV = InstructionConst.LDIV;
    public static final ArithmeticInstruction FDIV = InstructionConst.FDIV;
    public static final ArithmeticInstruction DDIV = InstructionConst.DDIV;
    public static final ArithmeticInstruction IREM = InstructionConst.IREM;
    public static final ArithmeticInstruction LREM = InstructionConst.LREM;
    public static final ArithmeticInstruction FREM = InstructionConst.FREM;
    public static final ArithmeticInstruction DREM = InstructionConst.DREM;
    public static final ArithmeticInstruction INEG = InstructionConst.INEG;
    public static final ArithmeticInstruction LNEG = InstructionConst.LNEG;
    public static final ArithmeticInstruction FNEG = InstructionConst.FNEG;
    public static final ArithmeticInstruction DNEG = InstructionConst.DNEG;
    public static final ArithmeticInstruction ISHL = InstructionConst.ISHL;
    public static final ArithmeticInstruction LSHL = InstructionConst.LSHL;
    public static final ArithmeticInstruction ISHR = InstructionConst.ISHR;
    public static final ArithmeticInstruction LSHR = InstructionConst.LSHR;
    public static final ArithmeticInstruction IUSHR = InstructionConst.IUSHR;
    public static final ArithmeticInstruction LUSHR = InstructionConst.LUSHR;
    public static final ArithmeticInstruction IAND = InstructionConst.IAND;
    public static final ArithmeticInstruction LAND = InstructionConst.LAND;
    public static final ArithmeticInstruction IOR = InstructionConst.IOR;
    public static final ArithmeticInstruction LOR = InstructionConst.LOR;
    public static final ArithmeticInstruction IXOR = InstructionConst.IXOR;
    public static final ArithmeticInstruction LXOR = InstructionConst.LXOR;
    public static final ConversionInstruction I2L = InstructionConst.I2L;
    public static final ConversionInstruction I2F = InstructionConst.I2F;
    public static final ConversionInstruction I2D = InstructionConst.I2D;
    public static final ConversionInstruction L2I = InstructionConst.L2I;
    public static final ConversionInstruction L2F = InstructionConst.L2F;
    public static final ConversionInstruction L2D = InstructionConst.L2D;
    public static final ConversionInstruction F2I = InstructionConst.F2I;
    public static final ConversionInstruction F2L = InstructionConst.F2L;
    public static final ConversionInstruction F2D = InstructionConst.F2D;
    public static final ConversionInstruction D2I = InstructionConst.D2I;
    public static final ConversionInstruction D2L = InstructionConst.D2L;
    public static final ConversionInstruction D2F = InstructionConst.D2F;
    public static final ConversionInstruction I2B = InstructionConst.I2B;
    public static final ConversionInstruction I2C = InstructionConst.I2C;
    public static final ConversionInstruction I2S = InstructionConst.I2S;
    public static final Instruction LCMP = InstructionConst.LCMP;
    public static final Instruction FCMPL = InstructionConst.FCMPL;
    public static final Instruction FCMPG = InstructionConst.FCMPG;
    public static final Instruction DCMPL = InstructionConst.DCMPL;
    public static final Instruction DCMPG = InstructionConst.DCMPG;
    public static final ReturnInstruction IRETURN = InstructionConst.IRETURN;
    public static final ReturnInstruction LRETURN = InstructionConst.LRETURN;
    public static final ReturnInstruction FRETURN = InstructionConst.FRETURN;
    public static final ReturnInstruction DRETURN = InstructionConst.DRETURN;
    public static final ReturnInstruction ARETURN = InstructionConst.ARETURN;
    public static final ReturnInstruction RETURN = InstructionConst.RETURN;
    public static final Instruction ARRAYLENGTH = InstructionConst.ARRAYLENGTH;
    public static final Instruction ATHROW = InstructionConst.ATHROW;
    public static final Instruction MONITORENTER = InstructionConst.MONITORENTER;
    public static final Instruction MONITOREXIT = InstructionConst.MONITOREXIT;
    public static final LocalVariableInstruction THIS = InstructionConst.THIS;
    public static final LocalVariableInstruction ALOAD_0 = InstructionConst.ALOAD_0;
    public static final LocalVariableInstruction ALOAD_1 = InstructionConst.ALOAD_1;
    public static final LocalVariableInstruction ALOAD_2 = InstructionConst.ALOAD_2;
    public static final LocalVariableInstruction ILOAD_0 = InstructionConst.ILOAD_0;
    public static final LocalVariableInstruction ILOAD_1 = InstructionConst.ILOAD_1;
    public static final LocalVariableInstruction ILOAD_2 = InstructionConst.ILOAD_2;
    public static final LocalVariableInstruction ASTORE_0 = InstructionConst.ASTORE_0;
    public static final LocalVariableInstruction ASTORE_1 = InstructionConst.ASTORE_1;
    public static final LocalVariableInstruction ASTORE_2 = InstructionConst.ASTORE_2;
    public static final LocalVariableInstruction ISTORE_0 = InstructionConst.ISTORE_0;
    public static final LocalVariableInstruction ISTORE_1 = InstructionConst.ISTORE_1;
    public static final LocalVariableInstruction ISTORE_2 = InstructionConst.ISTORE_2;
    public static final Instruction[] INSTRUCTIONS = InstructionConst.INSTRUCTIONS;
    public static final Clinit bla = new Clinit();

    public static class Clinit {
    }
}

