/*
 * Decompiled with CFR 0.152.
 */
package org.apache.bcel.generic;

import org.apache.bcel.generic.AALOAD;
import org.apache.bcel.generic.AASTORE;
import org.apache.bcel.generic.ACONST_NULL;
import org.apache.bcel.generic.ALOAD;
import org.apache.bcel.generic.ARETURN;
import org.apache.bcel.generic.ARRAYLENGTH;
import org.apache.bcel.generic.ASTORE;
import org.apache.bcel.generic.ATHROW;
import org.apache.bcel.generic.ArithmeticInstruction;
import org.apache.bcel.generic.ArrayInstruction;
import org.apache.bcel.generic.BALOAD;
import org.apache.bcel.generic.BASTORE;
import org.apache.bcel.generic.CALOAD;
import org.apache.bcel.generic.CASTORE;
import org.apache.bcel.generic.ConversionInstruction;
import org.apache.bcel.generic.D2F;
import org.apache.bcel.generic.D2I;
import org.apache.bcel.generic.D2L;
import org.apache.bcel.generic.DADD;
import org.apache.bcel.generic.DALOAD;
import org.apache.bcel.generic.DASTORE;
import org.apache.bcel.generic.DCMPG;
import org.apache.bcel.generic.DCMPL;
import org.apache.bcel.generic.DCONST;
import org.apache.bcel.generic.DDIV;
import org.apache.bcel.generic.DMUL;
import org.apache.bcel.generic.DNEG;
import org.apache.bcel.generic.DREM;
import org.apache.bcel.generic.DRETURN;
import org.apache.bcel.generic.DSUB;
import org.apache.bcel.generic.DUP;
import org.apache.bcel.generic.DUP2;
import org.apache.bcel.generic.DUP2_X1;
import org.apache.bcel.generic.DUP2_X2;
import org.apache.bcel.generic.DUP_X1;
import org.apache.bcel.generic.DUP_X2;
import org.apache.bcel.generic.F2D;
import org.apache.bcel.generic.F2I;
import org.apache.bcel.generic.F2L;
import org.apache.bcel.generic.FADD;
import org.apache.bcel.generic.FALOAD;
import org.apache.bcel.generic.FASTORE;
import org.apache.bcel.generic.FCMPG;
import org.apache.bcel.generic.FCMPL;
import org.apache.bcel.generic.FCONST;
import org.apache.bcel.generic.FDIV;
import org.apache.bcel.generic.FMUL;
import org.apache.bcel.generic.FNEG;
import org.apache.bcel.generic.FREM;
import org.apache.bcel.generic.FRETURN;
import org.apache.bcel.generic.FSUB;
import org.apache.bcel.generic.I2B;
import org.apache.bcel.generic.I2C;
import org.apache.bcel.generic.I2D;
import org.apache.bcel.generic.I2F;
import org.apache.bcel.generic.I2L;
import org.apache.bcel.generic.I2S;
import org.apache.bcel.generic.IADD;
import org.apache.bcel.generic.IALOAD;
import org.apache.bcel.generic.IAND;
import org.apache.bcel.generic.IASTORE;
import org.apache.bcel.generic.ICONST;
import org.apache.bcel.generic.IDIV;
import org.apache.bcel.generic.ILOAD;
import org.apache.bcel.generic.IMUL;
import org.apache.bcel.generic.INEG;
import org.apache.bcel.generic.IOR;
import org.apache.bcel.generic.IREM;
import org.apache.bcel.generic.IRETURN;
import org.apache.bcel.generic.ISHL;
import org.apache.bcel.generic.ISHR;
import org.apache.bcel.generic.ISTORE;
import org.apache.bcel.generic.ISUB;
import org.apache.bcel.generic.IUSHR;
import org.apache.bcel.generic.IXOR;
import org.apache.bcel.generic.Instruction;
import org.apache.bcel.generic.L2D;
import org.apache.bcel.generic.L2F;
import org.apache.bcel.generic.L2I;
import org.apache.bcel.generic.LADD;
import org.apache.bcel.generic.LALOAD;
import org.apache.bcel.generic.LAND;
import org.apache.bcel.generic.LASTORE;
import org.apache.bcel.generic.LCMP;
import org.apache.bcel.generic.LCONST;
import org.apache.bcel.generic.LDIV;
import org.apache.bcel.generic.LMUL;
import org.apache.bcel.generic.LNEG;
import org.apache.bcel.generic.LOR;
import org.apache.bcel.generic.LREM;
import org.apache.bcel.generic.LRETURN;
import org.apache.bcel.generic.LSHL;
import org.apache.bcel.generic.LSHR;
import org.apache.bcel.generic.LSUB;
import org.apache.bcel.generic.LUSHR;
import org.apache.bcel.generic.LXOR;
import org.apache.bcel.generic.LocalVariableInstruction;
import org.apache.bcel.generic.MONITORENTER;
import org.apache.bcel.generic.MONITOREXIT;
import org.apache.bcel.generic.NOP;
import org.apache.bcel.generic.POP;
import org.apache.bcel.generic.POP2;
import org.apache.bcel.generic.RETURN;
import org.apache.bcel.generic.ReturnInstruction;
import org.apache.bcel.generic.SALOAD;
import org.apache.bcel.generic.SASTORE;
import org.apache.bcel.generic.SWAP;
import org.apache.bcel.generic.StackInstruction;

public final class InstructionConst {
    public static final Instruction NOP = new NOP();
    public static final Instruction ACONST_NULL = new ACONST_NULL();
    public static final Instruction ICONST_M1 = new ICONST(-1);
    public static final Instruction ICONST_0 = new ICONST(0);
    public static final Instruction ICONST_1 = new ICONST(1);
    public static final Instruction ICONST_2 = new ICONST(2);
    public static final Instruction ICONST_3 = new ICONST(3);
    public static final Instruction ICONST_4 = new ICONST(4);
    public static final Instruction ICONST_5 = new ICONST(5);
    public static final Instruction LCONST_0 = new LCONST(0L);
    public static final Instruction LCONST_1 = new LCONST(1L);
    public static final Instruction FCONST_0 = new FCONST(0.0f);
    public static final Instruction FCONST_1 = new FCONST(1.0f);
    public static final Instruction FCONST_2 = new FCONST(2.0f);
    public static final Instruction DCONST_0 = new DCONST(0.0);
    public static final Instruction DCONST_1 = new DCONST(1.0);
    public static final ArrayInstruction IALOAD = new IALOAD();
    public static final ArrayInstruction LALOAD = new LALOAD();
    public static final ArrayInstruction FALOAD = new FALOAD();
    public static final ArrayInstruction DALOAD = new DALOAD();
    public static final ArrayInstruction AALOAD = new AALOAD();
    public static final ArrayInstruction BALOAD = new BALOAD();
    public static final ArrayInstruction CALOAD = new CALOAD();
    public static final ArrayInstruction SALOAD = new SALOAD();
    public static final ArrayInstruction IASTORE = new IASTORE();
    public static final ArrayInstruction LASTORE = new LASTORE();
    public static final ArrayInstruction FASTORE = new FASTORE();
    public static final ArrayInstruction DASTORE = new DASTORE();
    public static final ArrayInstruction AASTORE = new AASTORE();
    public static final ArrayInstruction BASTORE = new BASTORE();
    public static final ArrayInstruction CASTORE = new CASTORE();
    public static final ArrayInstruction SASTORE = new SASTORE();
    public static final StackInstruction POP = new POP();
    public static final StackInstruction POP2 = new POP2();
    public static final StackInstruction DUP = new DUP();
    public static final StackInstruction DUP_X1 = new DUP_X1();
    public static final StackInstruction DUP_X2 = new DUP_X2();
    public static final StackInstruction DUP2 = new DUP2();
    public static final StackInstruction DUP2_X1 = new DUP2_X1();
    public static final StackInstruction DUP2_X2 = new DUP2_X2();
    public static final StackInstruction SWAP = new SWAP();
    public static final ArithmeticInstruction IADD = new IADD();
    public static final ArithmeticInstruction LADD = new LADD();
    public static final ArithmeticInstruction FADD = new FADD();
    public static final ArithmeticInstruction DADD = new DADD();
    public static final ArithmeticInstruction ISUB = new ISUB();
    public static final ArithmeticInstruction LSUB = new LSUB();
    public static final ArithmeticInstruction FSUB = new FSUB();
    public static final ArithmeticInstruction DSUB = new DSUB();
    public static final ArithmeticInstruction IMUL = new IMUL();
    public static final ArithmeticInstruction LMUL = new LMUL();
    public static final ArithmeticInstruction FMUL = new FMUL();
    public static final ArithmeticInstruction DMUL = new DMUL();
    public static final ArithmeticInstruction IDIV = new IDIV();
    public static final ArithmeticInstruction LDIV = new LDIV();
    public static final ArithmeticInstruction FDIV = new FDIV();
    public static final ArithmeticInstruction DDIV = new DDIV();
    public static final ArithmeticInstruction IREM = new IREM();
    public static final ArithmeticInstruction LREM = new LREM();
    public static final ArithmeticInstruction FREM = new FREM();
    public static final ArithmeticInstruction DREM = new DREM();
    public static final ArithmeticInstruction INEG = new INEG();
    public static final ArithmeticInstruction LNEG = new LNEG();
    public static final ArithmeticInstruction FNEG = new FNEG();
    public static final ArithmeticInstruction DNEG = new DNEG();
    public static final ArithmeticInstruction ISHL = new ISHL();
    public static final ArithmeticInstruction LSHL = new LSHL();
    public static final ArithmeticInstruction ISHR = new ISHR();
    public static final ArithmeticInstruction LSHR = new LSHR();
    public static final ArithmeticInstruction IUSHR = new IUSHR();
    public static final ArithmeticInstruction LUSHR = new LUSHR();
    public static final ArithmeticInstruction IAND = new IAND();
    public static final ArithmeticInstruction LAND = new LAND();
    public static final ArithmeticInstruction IOR = new IOR();
    public static final ArithmeticInstruction LOR = new LOR();
    public static final ArithmeticInstruction IXOR = new IXOR();
    public static final ArithmeticInstruction LXOR = new LXOR();
    public static final ConversionInstruction I2L = new I2L();
    public static final ConversionInstruction I2F = new I2F();
    public static final ConversionInstruction I2D = new I2D();
    public static final ConversionInstruction L2I = new L2I();
    public static final ConversionInstruction L2F = new L2F();
    public static final ConversionInstruction L2D = new L2D();
    public static final ConversionInstruction F2I = new F2I();
    public static final ConversionInstruction F2L = new F2L();
    public static final ConversionInstruction F2D = new F2D();
    public static final ConversionInstruction D2I = new D2I();
    public static final ConversionInstruction D2L = new D2L();
    public static final ConversionInstruction D2F = new D2F();
    public static final ConversionInstruction I2B = new I2B();
    public static final ConversionInstruction I2C = new I2C();
    public static final ConversionInstruction I2S = new I2S();
    public static final Instruction LCMP = new LCMP();
    public static final Instruction FCMPL = new FCMPL();
    public static final Instruction FCMPG = new FCMPG();
    public static final Instruction DCMPL = new DCMPL();
    public static final Instruction DCMPG = new DCMPG();
    public static final ReturnInstruction IRETURN = new IRETURN();
    public static final ReturnInstruction LRETURN = new LRETURN();
    public static final ReturnInstruction FRETURN = new FRETURN();
    public static final ReturnInstruction DRETURN = new DRETURN();
    public static final ReturnInstruction ARETURN = new ARETURN();
    public static final ReturnInstruction RETURN = new RETURN();
    public static final Instruction ARRAYLENGTH = new ARRAYLENGTH();
    public static final Instruction ATHROW = new ATHROW();
    public static final Instruction MONITORENTER = new MONITORENTER();
    public static final Instruction MONITOREXIT = new MONITOREXIT();
    public static final LocalVariableInstruction THIS;
    public static final LocalVariableInstruction ALOAD_0;
    public static final LocalVariableInstruction ALOAD_1;
    public static final LocalVariableInstruction ALOAD_2;
    public static final LocalVariableInstruction ILOAD_0;
    public static final LocalVariableInstruction ILOAD_1;
    public static final LocalVariableInstruction ILOAD_2;
    public static final LocalVariableInstruction ASTORE_0;
    public static final LocalVariableInstruction ASTORE_1;
    public static final LocalVariableInstruction ASTORE_2;
    public static final LocalVariableInstruction ISTORE_0;
    public static final LocalVariableInstruction ISTORE_1;
    public static final LocalVariableInstruction ISTORE_2;
    static final Instruction[] INSTRUCTIONS;

    public static Instruction getInstruction(int index) {
        return INSTRUCTIONS[index];
    }

    private InstructionConst() {
    }

    static {
        ALOAD_0 = THIS = new ALOAD(0);
        ALOAD_1 = new ALOAD(1);
        ALOAD_2 = new ALOAD(2);
        ILOAD_0 = new ILOAD(0);
        ILOAD_1 = new ILOAD(1);
        ILOAD_2 = new ILOAD(2);
        ASTORE_0 = new ASTORE(0);
        ASTORE_1 = new ASTORE(1);
        ASTORE_2 = new ASTORE(2);
        ISTORE_0 = new ISTORE(0);
        ISTORE_1 = new ISTORE(1);
        ISTORE_2 = new ISTORE(2);
        INSTRUCTIONS = new Instruction[256];
        InstructionConst.INSTRUCTIONS[0] = NOP;
        InstructionConst.INSTRUCTIONS[1] = ACONST_NULL;
        InstructionConst.INSTRUCTIONS[2] = ICONST_M1;
        InstructionConst.INSTRUCTIONS[3] = ICONST_0;
        InstructionConst.INSTRUCTIONS[4] = ICONST_1;
        InstructionConst.INSTRUCTIONS[5] = ICONST_2;
        InstructionConst.INSTRUCTIONS[6] = ICONST_3;
        InstructionConst.INSTRUCTIONS[7] = ICONST_4;
        InstructionConst.INSTRUCTIONS[8] = ICONST_5;
        InstructionConst.INSTRUCTIONS[9] = LCONST_0;
        InstructionConst.INSTRUCTIONS[10] = LCONST_1;
        InstructionConst.INSTRUCTIONS[11] = FCONST_0;
        InstructionConst.INSTRUCTIONS[12] = FCONST_1;
        InstructionConst.INSTRUCTIONS[13] = FCONST_2;
        InstructionConst.INSTRUCTIONS[14] = DCONST_0;
        InstructionConst.INSTRUCTIONS[15] = DCONST_1;
        InstructionConst.INSTRUCTIONS[46] = IALOAD;
        InstructionConst.INSTRUCTIONS[47] = LALOAD;
        InstructionConst.INSTRUCTIONS[48] = FALOAD;
        InstructionConst.INSTRUCTIONS[49] = DALOAD;
        InstructionConst.INSTRUCTIONS[50] = AALOAD;
        InstructionConst.INSTRUCTIONS[51] = BALOAD;
        InstructionConst.INSTRUCTIONS[52] = CALOAD;
        InstructionConst.INSTRUCTIONS[53] = SALOAD;
        InstructionConst.INSTRUCTIONS[79] = IASTORE;
        InstructionConst.INSTRUCTIONS[80] = LASTORE;
        InstructionConst.INSTRUCTIONS[81] = FASTORE;
        InstructionConst.INSTRUCTIONS[82] = DASTORE;
        InstructionConst.INSTRUCTIONS[83] = AASTORE;
        InstructionConst.INSTRUCTIONS[84] = BASTORE;
        InstructionConst.INSTRUCTIONS[85] = CASTORE;
        InstructionConst.INSTRUCTIONS[86] = SASTORE;
        InstructionConst.INSTRUCTIONS[87] = POP;
        InstructionConst.INSTRUCTIONS[88] = POP2;
        InstructionConst.INSTRUCTIONS[89] = DUP;
        InstructionConst.INSTRUCTIONS[90] = DUP_X1;
        InstructionConst.INSTRUCTIONS[91] = DUP_X2;
        InstructionConst.INSTRUCTIONS[92] = DUP2;
        InstructionConst.INSTRUCTIONS[93] = DUP2_X1;
        InstructionConst.INSTRUCTIONS[94] = DUP2_X2;
        InstructionConst.INSTRUCTIONS[95] = SWAP;
        InstructionConst.INSTRUCTIONS[96] = IADD;
        InstructionConst.INSTRUCTIONS[97] = LADD;
        InstructionConst.INSTRUCTIONS[98] = FADD;
        InstructionConst.INSTRUCTIONS[99] = DADD;
        InstructionConst.INSTRUCTIONS[100] = ISUB;
        InstructionConst.INSTRUCTIONS[101] = LSUB;
        InstructionConst.INSTRUCTIONS[102] = FSUB;
        InstructionConst.INSTRUCTIONS[103] = DSUB;
        InstructionConst.INSTRUCTIONS[104] = IMUL;
        InstructionConst.INSTRUCTIONS[105] = LMUL;
        InstructionConst.INSTRUCTIONS[106] = FMUL;
        InstructionConst.INSTRUCTIONS[107] = DMUL;
        InstructionConst.INSTRUCTIONS[108] = IDIV;
        InstructionConst.INSTRUCTIONS[109] = LDIV;
        InstructionConst.INSTRUCTIONS[110] = FDIV;
        InstructionConst.INSTRUCTIONS[111] = DDIV;
        InstructionConst.INSTRUCTIONS[112] = IREM;
        InstructionConst.INSTRUCTIONS[113] = LREM;
        InstructionConst.INSTRUCTIONS[114] = FREM;
        InstructionConst.INSTRUCTIONS[115] = DREM;
        InstructionConst.INSTRUCTIONS[116] = INEG;
        InstructionConst.INSTRUCTIONS[117] = LNEG;
        InstructionConst.INSTRUCTIONS[118] = FNEG;
        InstructionConst.INSTRUCTIONS[119] = DNEG;
        InstructionConst.INSTRUCTIONS[120] = ISHL;
        InstructionConst.INSTRUCTIONS[121] = LSHL;
        InstructionConst.INSTRUCTIONS[122] = ISHR;
        InstructionConst.INSTRUCTIONS[123] = LSHR;
        InstructionConst.INSTRUCTIONS[124] = IUSHR;
        InstructionConst.INSTRUCTIONS[125] = LUSHR;
        InstructionConst.INSTRUCTIONS[126] = IAND;
        InstructionConst.INSTRUCTIONS[127] = LAND;
        InstructionConst.INSTRUCTIONS[128] = IOR;
        InstructionConst.INSTRUCTIONS[129] = LOR;
        InstructionConst.INSTRUCTIONS[130] = IXOR;
        InstructionConst.INSTRUCTIONS[131] = LXOR;
        InstructionConst.INSTRUCTIONS[133] = I2L;
        InstructionConst.INSTRUCTIONS[134] = I2F;
        InstructionConst.INSTRUCTIONS[135] = I2D;
        InstructionConst.INSTRUCTIONS[136] = L2I;
        InstructionConst.INSTRUCTIONS[137] = L2F;
        InstructionConst.INSTRUCTIONS[138] = L2D;
        InstructionConst.INSTRUCTIONS[139] = F2I;
        InstructionConst.INSTRUCTIONS[140] = F2L;
        InstructionConst.INSTRUCTIONS[141] = F2D;
        InstructionConst.INSTRUCTIONS[142] = D2I;
        InstructionConst.INSTRUCTIONS[143] = D2L;
        InstructionConst.INSTRUCTIONS[144] = D2F;
        InstructionConst.INSTRUCTIONS[145] = I2B;
        InstructionConst.INSTRUCTIONS[146] = I2C;
        InstructionConst.INSTRUCTIONS[147] = I2S;
        InstructionConst.INSTRUCTIONS[148] = LCMP;
        InstructionConst.INSTRUCTIONS[149] = FCMPL;
        InstructionConst.INSTRUCTIONS[150] = FCMPG;
        InstructionConst.INSTRUCTIONS[151] = DCMPL;
        InstructionConst.INSTRUCTIONS[152] = DCMPG;
        InstructionConst.INSTRUCTIONS[172] = IRETURN;
        InstructionConst.INSTRUCTIONS[173] = LRETURN;
        InstructionConst.INSTRUCTIONS[174] = FRETURN;
        InstructionConst.INSTRUCTIONS[175] = DRETURN;
        InstructionConst.INSTRUCTIONS[176] = ARETURN;
        InstructionConst.INSTRUCTIONS[177] = RETURN;
        InstructionConst.INSTRUCTIONS[190] = ARRAYLENGTH;
        InstructionConst.INSTRUCTIONS[191] = ATHROW;
        InstructionConst.INSTRUCTIONS[194] = MONITORENTER;
        InstructionConst.INSTRUCTIONS[195] = MONITOREXIT;
    }
}

