/*
 * Decompiled with CFR 0.152.
 */
package org.apache.xalan.xsltc.runtime;

import java.util.ListResourceBundle;

public class ErrorMessages_sk
extends ListResourceBundle {
    @Override
    public Object[][] getContents() {
        return new Object[][]{{"RUN_TIME_INTERNAL_ERR", "V ''{0}'' sa vyskytla intern\u00e1 runtime chyba"}, {"RUN_TIME_COPY_ERR", "Chyba \u010dasu spustenia pri sp\u00fa\u0161\u0165an\u00ed <xsl:copy>."}, {"DATA_CONVERSION_ERR", "Konverzia z ''{0}'' na ''{1}'' je neplatn\u00e1."}, {"EXTERNAL_FUNC_ERR", "XLTC nepodporuje extern\u00fa funkciu ''{0}''."}, {"EQUALITY_EXPR_ERR", "Nezn\u00e1my typ argumentu je v\u00fdrazom rovnosti."}, {"INVALID_ARGUMENT_ERR", "Vo volan\u00ed do ''{1}'' je neplatn\u00fd typ argumentu ''{0}'' "}, {"FORMAT_NUMBER_ERR", "Prebieha pokus o form\u00e1tovanie \u010d\u00edsla ''{0}'' pomocou vzoru ''{1}''."}, {"ITERATOR_CLONE_ERR", "Iter\u00e1tor ''{0}'' sa ned\u00e1 klonova\u0165."}, {"AXIS_SUPPORT_ERR", "Iter\u00e1tor pre os ''{0}'' nie je podporovan\u00fd."}, {"TYPED_AXIS_SUPPORT_ERR", "Iter\u00e1tor pre zadan\u00fa os ''{0}'' nie je podporovan\u00fd."}, {"STRAY_ATTRIBUTE_ERR", "Atrib\u00fat ''{0}'' je mimo prvku."}, {"STRAY_NAMESPACE_ERR", "Deklar\u00e1cia n\u00e1zvov\u00e9ho priestoru ''{0}''=''{1}'' je mimo prvku."}, {"NAMESPACE_PREFIX_ERR", "N\u00e1zvov\u00fd priestor pre predponu ''{0}'' nebol deklarovan\u00fd."}, {"DOM_ADAPTER_INIT_ERR", "DOMAdapter bol vytvoren\u00fd pomocou nespr\u00e1vneho typu zdrojov\u00e9ho DOM."}, {"PARSER_DTD_SUPPORT_ERR", "Analyz\u00e1tor SAX, ktor\u00fd pou\u017e\u00edvate, nesprac\u00fava udalosti deklar\u00e1cie DTD."}, {"NAMESPACES_SUPPORT_ERR", "Analyz\u00e1tor SAX, ktor\u00fd pou\u017e\u00edvate, nem\u00e1 podporu pre n\u00e1zvov\u00e9 priestory XML."}, {"CANT_RESOLVE_RELATIVE_URI_ERR", "Nebolo mo\u017en\u00e9 rozl\u00ed\u0161i\u0165 odkaz na URI ''{0}''."}, {"UNSUPPORTED_XSL_ERR", "XSL prvok ''{0}'' nie je podporovan\u00fd"}, {"UNSUPPORTED_EXT_ERR", "XSLTC pr\u00edpona ''{0}'' nebola rozpoznan\u00e1"}, {"UNKNOWN_TRANSLET_VERSION_ERR", "\u0160pecifikovan\u00fd translet ''{0}'' bol vytvoren\u00fd pomocou verzie XSLTC, ktor\u00e1 je nov\u0161ia ako verzia XSLTC runtime, ktor\u00fd sa pou\u017e\u00edva.  Mus\u00edte prekompilova\u0165 defin\u00edcie \u0161t\u00fdlov (objekt stylesheet) alebo pou\u017ei\u0165 na spustenie tohto transletu nov\u0161iu verziu n\u00e1stroja XSLTC."}, {"INVALID_QNAME_ERR", "Atrib\u00fat, ktor\u00fd mus\u00ed ma\u0165 hodnotu QName, mal hodnotu ''{0}''"}, {"INVALID_NCNAME_ERR", "Atrib\u00fat, ktor\u00fd mus\u00ed ma\u0165 hodnotu NCName, mal hodnotu ''{0}''"}, {"UNALLOWED_EXTENSION_FUNCTION_ERR", "Pou\u017e\u00edvanie funkcie roz\u0161\u00edrenia ''{0}'' nie je povolen\u00e9, ke\u010f je funkcia bezpe\u010dn\u00e9ho spracovania nastaven\u00e1 na hodnotu true."}, {"UNALLOWED_EXTENSION_ELEMENT_ERR", "Pou\u017e\u00edvanie prvku roz\u0161\u00edrenia ''{0}'' nie je povolen\u00e9, ke\u010f je funkcia bezpe\u010dn\u00e9ho spracovania nastaven\u00e1 na hodnotu true."}};
    }
}

