/*
 * Decompiled with CFR 0.152.
 */
package com.atlassian.troubleshooting.preupgrade;

public enum AnalyticsKey {
    UNSUPPORTED_COLLATION,
    UNSUPPORTED_DATABASE,
    UNSUPPORTED_JAVA,
    UNSUPPORTED_GIT,
    UNSUPPORTED_SEARCH,
    UNSUPPORTED_OPERATING_SYSTEM,
    NO_SUPPORTED_PLATFORMS,
    NEW_LICENSE_REQUIRED,
    UPGRADE_TO_DC_LICENSE_REQUIRED,
    PRE_UPGRADE_CHECKS,
    UPGRADE_METHOD,
    TEST_UPGRADE,
    PRODUCTION_UPGRADE,
    POST_UPGRADE,
    SUCCESS,
    PRODUCTION_UPGRADE_ZDU,
    TEST_UPGRADE_ZDU;

}

