/*
 * Decompiled with CFR 0.152.
 */
package com.ibm.wsdl.extensions;

import com.ibm.wsdl.extensions.http.HTTPAddressImpl;
import com.ibm.wsdl.extensions.http.HTTPAddressSerializer;
import com.ibm.wsdl.extensions.http.HTTPBindingImpl;
import com.ibm.wsdl.extensions.http.HTTPBindingSerializer;
import com.ibm.wsdl.extensions.http.HTTPConstants;
import com.ibm.wsdl.extensions.http.HTTPOperationImpl;
import com.ibm.wsdl.extensions.http.HTTPOperationSerializer;
import com.ibm.wsdl.extensions.http.HTTPUrlEncodedImpl;
import com.ibm.wsdl.extensions.http.HTTPUrlEncodedSerializer;
import com.ibm.wsdl.extensions.http.HTTPUrlReplacementImpl;
import com.ibm.wsdl.extensions.http.HTTPUrlReplacementSerializer;
import com.ibm.wsdl.extensions.mime.MIMEConstants;
import com.ibm.wsdl.extensions.mime.MIMEContentImpl;
import com.ibm.wsdl.extensions.mime.MIMEContentSerializer;
import com.ibm.wsdl.extensions.mime.MIMEMimeXmlImpl;
import com.ibm.wsdl.extensions.mime.MIMEMimeXmlSerializer;
import com.ibm.wsdl.extensions.mime.MIMEMultipartRelatedImpl;
import com.ibm.wsdl.extensions.mime.MIMEMultipartRelatedSerializer;
import com.ibm.wsdl.extensions.mime.MIMEPartImpl;
import com.ibm.wsdl.extensions.schema.SchemaConstants;
import com.ibm.wsdl.extensions.schema.SchemaDeserializer;
import com.ibm.wsdl.extensions.schema.SchemaImpl;
import com.ibm.wsdl.extensions.schema.SchemaSerializer;
import com.ibm.wsdl.extensions.soap.SOAPAddressImpl;
import com.ibm.wsdl.extensions.soap.SOAPAddressSerializer;
import com.ibm.wsdl.extensions.soap.SOAPBindingImpl;
import com.ibm.wsdl.extensions.soap.SOAPBindingSerializer;
import com.ibm.wsdl.extensions.soap.SOAPBodyImpl;
import com.ibm.wsdl.extensions.soap.SOAPBodySerializer;
import com.ibm.wsdl.extensions.soap.SOAPConstants;
import com.ibm.wsdl.extensions.soap.SOAPFaultImpl;
import com.ibm.wsdl.extensions.soap.SOAPFaultSerializer;
import com.ibm.wsdl.extensions.soap.SOAPHeaderFaultImpl;
import com.ibm.wsdl.extensions.soap.SOAPHeaderImpl;
import com.ibm.wsdl.extensions.soap.SOAPHeaderSerializer;
import com.ibm.wsdl.extensions.soap.SOAPOperationImpl;
import com.ibm.wsdl.extensions.soap.SOAPOperationSerializer;
import com.ibm.wsdl.extensions.soap12.SOAP12AddressImpl;
import com.ibm.wsdl.extensions.soap12.SOAP12AddressSerializer;
import com.ibm.wsdl.extensions.soap12.SOAP12BindingImpl;
import com.ibm.wsdl.extensions.soap12.SOAP12BindingSerializer;
import com.ibm.wsdl.extensions.soap12.SOAP12BodyImpl;
import com.ibm.wsdl.extensions.soap12.SOAP12BodySerializer;
import com.ibm.wsdl.extensions.soap12.SOAP12Constants;
import com.ibm.wsdl.extensions.soap12.SOAP12FaultImpl;
import com.ibm.wsdl.extensions.soap12.SOAP12FaultSerializer;
import com.ibm.wsdl.extensions.soap12.SOAP12HeaderFaultImpl;
import com.ibm.wsdl.extensions.soap12.SOAP12HeaderImpl;
import com.ibm.wsdl.extensions.soap12.SOAP12HeaderSerializer;
import com.ibm.wsdl.extensions.soap12.SOAP12OperationImpl;
import com.ibm.wsdl.extensions.soap12.SOAP12OperationSerializer;
import javax.wsdl.Binding;
import javax.wsdl.BindingFault;
import javax.wsdl.BindingInput;
import javax.wsdl.BindingOperation;
import javax.wsdl.BindingOutput;
import javax.wsdl.Port;
import javax.wsdl.Types;
import javax.wsdl.extensions.ExtensionRegistry;
import javax.wsdl.extensions.mime.MIMEMultipartRelated;
import javax.wsdl.extensions.mime.MIMEPart;
import javax.wsdl.extensions.soap.SOAPHeader;
import javax.wsdl.extensions.soap12.SOAP12Header;

public class PopulatedExtensionRegistry
extends ExtensionRegistry {
    public static final long serialVersionUID = 1L;

    public PopulatedExtensionRegistry() {
        SOAPAddressSerializer soapAddressSer = new SOAPAddressSerializer();
        this.registerSerializer(Port.class, SOAPConstants.Q_ELEM_SOAP_ADDRESS, soapAddressSer);
        this.registerDeserializer(Port.class, SOAPConstants.Q_ELEM_SOAP_ADDRESS, soapAddressSer);
        this.mapExtensionTypes(Port.class, SOAPConstants.Q_ELEM_SOAP_ADDRESS, SOAPAddressImpl.class);
        SOAPBindingSerializer soapBindingSer = new SOAPBindingSerializer();
        this.registerSerializer(Binding.class, SOAPConstants.Q_ELEM_SOAP_BINDING, soapBindingSer);
        this.registerDeserializer(Binding.class, SOAPConstants.Q_ELEM_SOAP_BINDING, soapBindingSer);
        this.mapExtensionTypes(Binding.class, SOAPConstants.Q_ELEM_SOAP_BINDING, SOAPBindingImpl.class);
        SOAPHeaderSerializer soapHeaderSer = new SOAPHeaderSerializer();
        this.registerSerializer(BindingInput.class, SOAPConstants.Q_ELEM_SOAP_HEADER, soapHeaderSer);
        this.registerDeserializer(BindingInput.class, SOAPConstants.Q_ELEM_SOAP_HEADER, soapHeaderSer);
        this.mapExtensionTypes(BindingInput.class, SOAPConstants.Q_ELEM_SOAP_HEADER, SOAPHeaderImpl.class);
        this.registerSerializer(BindingOutput.class, SOAPConstants.Q_ELEM_SOAP_HEADER, soapHeaderSer);
        this.registerDeserializer(BindingOutput.class, SOAPConstants.Q_ELEM_SOAP_HEADER, soapHeaderSer);
        this.mapExtensionTypes(BindingOutput.class, SOAPConstants.Q_ELEM_SOAP_HEADER, SOAPHeaderImpl.class);
        this.mapExtensionTypes(SOAPHeader.class, SOAPConstants.Q_ELEM_SOAP_HEADER_FAULT, SOAPHeaderFaultImpl.class);
        this.registerSerializer(MIMEPart.class, SOAPConstants.Q_ELEM_SOAP_HEADER, soapHeaderSer);
        this.registerDeserializer(MIMEPart.class, SOAPConstants.Q_ELEM_SOAP_HEADER, soapHeaderSer);
        this.mapExtensionTypes(MIMEPart.class, SOAPConstants.Q_ELEM_SOAP_HEADER, SOAPHeaderImpl.class);
        SOAPBodySerializer soapBodySer = new SOAPBodySerializer();
        this.registerSerializer(BindingInput.class, SOAPConstants.Q_ELEM_SOAP_BODY, soapBodySer);
        this.registerDeserializer(BindingInput.class, SOAPConstants.Q_ELEM_SOAP_BODY, soapBodySer);
        this.mapExtensionTypes(BindingInput.class, SOAPConstants.Q_ELEM_SOAP_BODY, SOAPBodyImpl.class);
        this.registerSerializer(BindingOutput.class, SOAPConstants.Q_ELEM_SOAP_BODY, soapBodySer);
        this.registerDeserializer(BindingOutput.class, SOAPConstants.Q_ELEM_SOAP_BODY, soapBodySer);
        this.mapExtensionTypes(BindingOutput.class, SOAPConstants.Q_ELEM_SOAP_BODY, SOAPBodyImpl.class);
        this.registerSerializer(MIMEPart.class, SOAPConstants.Q_ELEM_SOAP_BODY, soapBodySer);
        this.registerDeserializer(MIMEPart.class, SOAPConstants.Q_ELEM_SOAP_BODY, soapBodySer);
        this.mapExtensionTypes(MIMEPart.class, SOAPConstants.Q_ELEM_SOAP_BODY, SOAPBodyImpl.class);
        SOAPFaultSerializer soapFaultSer = new SOAPFaultSerializer();
        this.registerSerializer(BindingFault.class, SOAPConstants.Q_ELEM_SOAP_FAULT, soapFaultSer);
        this.registerDeserializer(BindingFault.class, SOAPConstants.Q_ELEM_SOAP_FAULT, soapFaultSer);
        this.mapExtensionTypes(BindingFault.class, SOAPConstants.Q_ELEM_SOAP_FAULT, SOAPFaultImpl.class);
        SOAPOperationSerializer soapOperationSer = new SOAPOperationSerializer();
        this.registerSerializer(BindingOperation.class, SOAPConstants.Q_ELEM_SOAP_OPERATION, soapOperationSer);
        this.registerDeserializer(BindingOperation.class, SOAPConstants.Q_ELEM_SOAP_OPERATION, soapOperationSer);
        this.mapExtensionTypes(BindingOperation.class, SOAPConstants.Q_ELEM_SOAP_OPERATION, SOAPOperationImpl.class);
        SOAP12AddressSerializer soap12AddressSer = new SOAP12AddressSerializer();
        this.registerSerializer(Port.class, SOAP12Constants.Q_ELEM_SOAP_ADDRESS, soap12AddressSer);
        this.registerDeserializer(Port.class, SOAP12Constants.Q_ELEM_SOAP_ADDRESS, soap12AddressSer);
        this.mapExtensionTypes(Port.class, SOAP12Constants.Q_ELEM_SOAP_ADDRESS, SOAP12AddressImpl.class);
        SOAP12BindingSerializer soap12BindingSer = new SOAP12BindingSerializer();
        this.registerSerializer(Binding.class, SOAP12Constants.Q_ELEM_SOAP_BINDING, soap12BindingSer);
        this.registerDeserializer(Binding.class, SOAP12Constants.Q_ELEM_SOAP_BINDING, soap12BindingSer);
        this.mapExtensionTypes(Binding.class, SOAP12Constants.Q_ELEM_SOAP_BINDING, SOAP12BindingImpl.class);
        SOAP12HeaderSerializer soap12HeaderSer = new SOAP12HeaderSerializer();
        this.registerSerializer(BindingInput.class, SOAP12Constants.Q_ELEM_SOAP_HEADER, soap12HeaderSer);
        this.registerDeserializer(BindingInput.class, SOAP12Constants.Q_ELEM_SOAP_HEADER, soap12HeaderSer);
        this.mapExtensionTypes(BindingInput.class, SOAP12Constants.Q_ELEM_SOAP_HEADER, SOAP12HeaderImpl.class);
        this.registerSerializer(BindingOutput.class, SOAP12Constants.Q_ELEM_SOAP_HEADER, soap12HeaderSer);
        this.registerDeserializer(BindingOutput.class, SOAP12Constants.Q_ELEM_SOAP_HEADER, soap12HeaderSer);
        this.mapExtensionTypes(BindingOutput.class, SOAP12Constants.Q_ELEM_SOAP_HEADER, SOAP12HeaderImpl.class);
        this.mapExtensionTypes(SOAP12Header.class, SOAP12Constants.Q_ELEM_SOAP_HEADER_FAULT, SOAP12HeaderFaultImpl.class);
        this.registerSerializer(MIMEPart.class, SOAP12Constants.Q_ELEM_SOAP_HEADER, soap12HeaderSer);
        this.registerDeserializer(MIMEPart.class, SOAP12Constants.Q_ELEM_SOAP_HEADER, soap12HeaderSer);
        this.mapExtensionTypes(MIMEPart.class, SOAP12Constants.Q_ELEM_SOAP_HEADER, SOAP12HeaderImpl.class);
        SOAP12BodySerializer soap12BodySer = new SOAP12BodySerializer();
        this.registerSerializer(BindingInput.class, SOAP12Constants.Q_ELEM_SOAP_BODY, soap12BodySer);
        this.registerDeserializer(BindingInput.class, SOAP12Constants.Q_ELEM_SOAP_BODY, soap12BodySer);
        this.mapExtensionTypes(BindingInput.class, SOAP12Constants.Q_ELEM_SOAP_BODY, SOAP12BodyImpl.class);
        this.registerSerializer(BindingOutput.class, SOAP12Constants.Q_ELEM_SOAP_BODY, soap12BodySer);
        this.registerDeserializer(BindingOutput.class, SOAP12Constants.Q_ELEM_SOAP_BODY, soap12BodySer);
        this.mapExtensionTypes(BindingOutput.class, SOAP12Constants.Q_ELEM_SOAP_BODY, SOAP12BodyImpl.class);
        this.registerSerializer(MIMEPart.class, SOAP12Constants.Q_ELEM_SOAP_BODY, soap12BodySer);
        this.registerDeserializer(MIMEPart.class, SOAP12Constants.Q_ELEM_SOAP_BODY, soap12BodySer);
        this.mapExtensionTypes(MIMEPart.class, SOAP12Constants.Q_ELEM_SOAP_BODY, SOAP12BodyImpl.class);
        SOAP12FaultSerializer soap12FaultSer = new SOAP12FaultSerializer();
        this.registerSerializer(BindingFault.class, SOAP12Constants.Q_ELEM_SOAP_FAULT, soap12FaultSer);
        this.registerDeserializer(BindingFault.class, SOAP12Constants.Q_ELEM_SOAP_FAULT, soap12FaultSer);
        this.mapExtensionTypes(BindingFault.class, SOAP12Constants.Q_ELEM_SOAP_FAULT, SOAP12FaultImpl.class);
        SOAP12OperationSerializer soap12OperationSer = new SOAP12OperationSerializer();
        this.registerSerializer(BindingOperation.class, SOAP12Constants.Q_ELEM_SOAP_OPERATION, soap12OperationSer);
        this.registerDeserializer(BindingOperation.class, SOAP12Constants.Q_ELEM_SOAP_OPERATION, soap12OperationSer);
        this.mapExtensionTypes(BindingOperation.class, SOAP12Constants.Q_ELEM_SOAP_OPERATION, SOAP12OperationImpl.class);
        HTTPAddressSerializer httpAddressSer = new HTTPAddressSerializer();
        this.registerSerializer(Port.class, HTTPConstants.Q_ELEM_HTTP_ADDRESS, httpAddressSer);
        this.registerDeserializer(Port.class, HTTPConstants.Q_ELEM_HTTP_ADDRESS, httpAddressSer);
        this.mapExtensionTypes(Port.class, HTTPConstants.Q_ELEM_HTTP_ADDRESS, HTTPAddressImpl.class);
        HTTPOperationSerializer httpOperationSer = new HTTPOperationSerializer();
        this.registerSerializer(BindingOperation.class, HTTPConstants.Q_ELEM_HTTP_OPERATION, httpOperationSer);
        this.registerDeserializer(BindingOperation.class, HTTPConstants.Q_ELEM_HTTP_OPERATION, httpOperationSer);
        this.mapExtensionTypes(BindingOperation.class, HTTPConstants.Q_ELEM_HTTP_OPERATION, HTTPOperationImpl.class);
        HTTPBindingSerializer httpBindingSer = new HTTPBindingSerializer();
        this.registerSerializer(Binding.class, HTTPConstants.Q_ELEM_HTTP_BINDING, httpBindingSer);
        this.registerDeserializer(Binding.class, HTTPConstants.Q_ELEM_HTTP_BINDING, httpBindingSer);
        this.mapExtensionTypes(Binding.class, HTTPConstants.Q_ELEM_HTTP_BINDING, HTTPBindingImpl.class);
        HTTPUrlEncodedSerializer httpUrlEncodedSer = new HTTPUrlEncodedSerializer();
        this.registerSerializer(BindingInput.class, HTTPConstants.Q_ELEM_HTTP_URL_ENCODED, httpUrlEncodedSer);
        this.registerDeserializer(BindingInput.class, HTTPConstants.Q_ELEM_HTTP_URL_ENCODED, httpUrlEncodedSer);
        this.mapExtensionTypes(BindingInput.class, HTTPConstants.Q_ELEM_HTTP_URL_ENCODED, HTTPUrlEncodedImpl.class);
        HTTPUrlReplacementSerializer httpUrlReplacementSer = new HTTPUrlReplacementSerializer();
        this.registerSerializer(BindingInput.class, HTTPConstants.Q_ELEM_HTTP_URL_REPLACEMENT, httpUrlReplacementSer);
        this.registerDeserializer(BindingInput.class, HTTPConstants.Q_ELEM_HTTP_URL_REPLACEMENT, httpUrlReplacementSer);
        this.mapExtensionTypes(BindingInput.class, HTTPConstants.Q_ELEM_HTTP_URL_REPLACEMENT, HTTPUrlReplacementImpl.class);
        MIMEContentSerializer mimeContentSer = new MIMEContentSerializer();
        this.registerSerializer(BindingInput.class, MIMEConstants.Q_ELEM_MIME_CONTENT, mimeContentSer);
        this.registerDeserializer(BindingInput.class, MIMEConstants.Q_ELEM_MIME_CONTENT, mimeContentSer);
        this.mapExtensionTypes(BindingInput.class, MIMEConstants.Q_ELEM_MIME_CONTENT, MIMEContentImpl.class);
        this.registerSerializer(BindingOutput.class, MIMEConstants.Q_ELEM_MIME_CONTENT, mimeContentSer);
        this.registerDeserializer(BindingOutput.class, MIMEConstants.Q_ELEM_MIME_CONTENT, mimeContentSer);
        this.mapExtensionTypes(BindingOutput.class, MIMEConstants.Q_ELEM_MIME_CONTENT, MIMEContentImpl.class);
        this.registerSerializer(MIMEPart.class, MIMEConstants.Q_ELEM_MIME_CONTENT, mimeContentSer);
        this.registerDeserializer(MIMEPart.class, MIMEConstants.Q_ELEM_MIME_CONTENT, mimeContentSer);
        this.mapExtensionTypes(MIMEPart.class, MIMEConstants.Q_ELEM_MIME_CONTENT, MIMEContentImpl.class);
        MIMEMultipartRelatedSerializer mimeMultipartRelatedSer = new MIMEMultipartRelatedSerializer();
        this.registerSerializer(BindingInput.class, MIMEConstants.Q_ELEM_MIME_MULTIPART_RELATED, mimeMultipartRelatedSer);
        this.registerDeserializer(BindingInput.class, MIMEConstants.Q_ELEM_MIME_MULTIPART_RELATED, mimeMultipartRelatedSer);
        this.mapExtensionTypes(BindingInput.class, MIMEConstants.Q_ELEM_MIME_MULTIPART_RELATED, MIMEMultipartRelatedImpl.class);
        this.registerSerializer(BindingOutput.class, MIMEConstants.Q_ELEM_MIME_MULTIPART_RELATED, mimeMultipartRelatedSer);
        this.registerDeserializer(BindingOutput.class, MIMEConstants.Q_ELEM_MIME_MULTIPART_RELATED, mimeMultipartRelatedSer);
        this.mapExtensionTypes(BindingOutput.class, MIMEConstants.Q_ELEM_MIME_MULTIPART_RELATED, MIMEMultipartRelatedImpl.class);
        this.registerSerializer(MIMEPart.class, MIMEConstants.Q_ELEM_MIME_MULTIPART_RELATED, mimeMultipartRelatedSer);
        this.registerDeserializer(MIMEPart.class, MIMEConstants.Q_ELEM_MIME_MULTIPART_RELATED, mimeMultipartRelatedSer);
        this.mapExtensionTypes(MIMEPart.class, MIMEConstants.Q_ELEM_MIME_MULTIPART_RELATED, MIMEMultipartRelatedImpl.class);
        this.mapExtensionTypes(MIMEMultipartRelated.class, MIMEConstants.Q_ELEM_MIME_PART, MIMEPartImpl.class);
        MIMEMimeXmlSerializer mimeMimeXmlSer = new MIMEMimeXmlSerializer();
        this.registerSerializer(BindingInput.class, MIMEConstants.Q_ELEM_MIME_MIME_XML, mimeMimeXmlSer);
        this.registerDeserializer(BindingInput.class, MIMEConstants.Q_ELEM_MIME_MIME_XML, mimeMimeXmlSer);
        this.mapExtensionTypes(BindingInput.class, MIMEConstants.Q_ELEM_MIME_MIME_XML, MIMEMimeXmlImpl.class);
        this.registerSerializer(BindingOutput.class, MIMEConstants.Q_ELEM_MIME_MIME_XML, mimeMimeXmlSer);
        this.registerDeserializer(BindingOutput.class, MIMEConstants.Q_ELEM_MIME_MIME_XML, mimeMimeXmlSer);
        this.mapExtensionTypes(BindingOutput.class, MIMEConstants.Q_ELEM_MIME_MIME_XML, MIMEMimeXmlImpl.class);
        this.registerSerializer(MIMEPart.class, MIMEConstants.Q_ELEM_MIME_MIME_XML, mimeMimeXmlSer);
        this.registerDeserializer(MIMEPart.class, MIMEConstants.Q_ELEM_MIME_MIME_XML, mimeMimeXmlSer);
        this.mapExtensionTypes(MIMEPart.class, MIMEConstants.Q_ELEM_MIME_MIME_XML, MIMEMimeXmlImpl.class);
        this.mapExtensionTypes(Types.class, SchemaConstants.Q_ELEM_XSD_1999, SchemaImpl.class);
        this.registerDeserializer(Types.class, SchemaConstants.Q_ELEM_XSD_1999, new SchemaDeserializer());
        this.registerSerializer(Types.class, SchemaConstants.Q_ELEM_XSD_1999, new SchemaSerializer());
        this.mapExtensionTypes(Types.class, SchemaConstants.Q_ELEM_XSD_2000, SchemaImpl.class);
        this.registerDeserializer(Types.class, SchemaConstants.Q_ELEM_XSD_2000, new SchemaDeserializer());
        this.registerSerializer(Types.class, SchemaConstants.Q_ELEM_XSD_2000, new SchemaSerializer());
        this.mapExtensionTypes(Types.class, SchemaConstants.Q_ELEM_XSD_2001, SchemaImpl.class);
        this.registerDeserializer(Types.class, SchemaConstants.Q_ELEM_XSD_2001, new SchemaDeserializer());
        this.registerSerializer(Types.class, SchemaConstants.Q_ELEM_XSD_2001, new SchemaSerializer());
    }
}

