/*
 * Decompiled with CFR 0.152.
 */
package org.apache.tomcat.dbcp.dbcp2.cpdsadapter;

import org.apache.tomcat.dbcp.dbcp2.PStmtKey;

@Deprecated
public class PStmtKeyCPDS
extends PStmtKey {
    public PStmtKeyCPDS(String sql) {
        super(sql);
    }

    public PStmtKeyCPDS(String sql, int autoGeneratedKeys) {
        super(sql, null, autoGeneratedKeys);
    }

    public PStmtKeyCPDS(String sql, int resultSetType, int resultSetConcurrency) {
        super(sql, resultSetType, resultSetConcurrency);
    }

    public PStmtKeyCPDS(String sql, int resultSetType, int resultSetConcurrency, int resultSetHoldability) {
        super(sql, null, resultSetType, resultSetConcurrency, resultSetHoldability);
    }

    public PStmtKeyCPDS(String sql, int[] columnIndexes) {
        super(sql, null, columnIndexes);
    }

    public PStmtKeyCPDS(String sql, String[] columnNames) {
        super(sql, null, columnNames);
    }
}

